run:
  timeout: 5m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: github.com/swaggo/swag
      linters:
        - goanalysis_metalinter
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - ineffassign
    - gofmt
