version: '3.8'

services:
  smarters:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./test.db:/var/lib/sqlite/test.db
