// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/webhook": {
            "post": {
                "description": "Recebe mensagens do Messenger e responde com texto ou botões",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Processa mensagens recebidas do Messenger",
                "parameters": [
                    {
                        "description": "Mensagem recebida",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.MessageReceived"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MessageSent"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Attachment": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/main.Payload"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.Button": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.Content": {
            "type": "object",
            "properties": {
                "attachment": {
                    "$ref": "#/definitions/main.Attachment"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "main.Message": {
            "type": "object",
            "properties": {
                "mid": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "main.MessageReceived": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "messaging": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Messaging"
                    }
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "main.MessageSent": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/main.Content"
                },
                "recipient": {
                    "$ref": "#/definitions/main.User"
                }
            }
        },
        "main.Messaging": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/main.Message"
                },
                "postback": {
                    "$ref": "#/definitions/main.Postback"
                },
                "recipient": {
                    "$ref": "#/definitions/main.User"
                },
                "sender": {
                    "$ref": "#/definitions/main.User"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "main.Payload": {
            "type": "object",
            "properties": {
                "buttons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Button"
                    }
                },
                "template_type": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "main.Postback": {
            "type": "object",
            "properties": {
                "mid": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                }
            }
        },
        "main.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Smarters API",
	Description:      "API para receber e tratar mensagens enviadas pelo Messenger da Meta.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
