name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: go mod tidy

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.45.2
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Verify golangci-lint installation
      run: golangci-lint --version

    - name: Install gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@v2.15.0
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Verify gosec installation
      run: gosec --version

    - name: Run security checks
      run: gosec ./...

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -v ./...
