name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Install dependencies
      run: go mod tidy

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Install gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@v2.15.0
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run security checks
      run: gosec ./...

    - name: Build Docker image
      run: docker build -t smarters .

    - name: Create Docker Compose file
      run: |
        echo "version: '3.8'" > docker-compose.yml
        echo "services:" >> docker-compose.yml
        echo "  smarters:" >> docker-compose.yml
        echo "    image: smarters" >> docker-compose.yml
        echo "    ports:" >> docker-compose.yml
        echo "      - '8080:8080'" >> docker-compose.yml

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for the server to be ready
      run: |
        set -e
        until curl --output /dev/null --silent --fail http://localhost:8080; do
          echo 'Waiting for server...'
          sleep 2
        done
        echo 'Server is up and running!'

    - name: Run tests
      run: go test ./...

    - name: Display Docker logs
      run: docker-compose logs

    - name: Clean up
      run: docker-compose down
