name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@v2.15.0

    - name: Install dependencies
      run: go mod tidy

    - name: Run lint
      run: golangci-lint run

    - name: Run security checks
      run: gosec ./...

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -v ./...
